/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\multi.glb 
*/

import React, { useRef, useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import path from '../assets/3D/multi.glb'

export default function Model({ animation, ...props }) {
  const group = React.useRef()
  const { scene, animations } = useGLTF(path)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    Object.values(actions).forEach((action) => action.stop());
  
    if (actions[animation]) {
      actions[animation].reset().play();
  
      const timeAnim = (actions[animation]._clip?.duration || 0) * 1000;
      console.log(timeAnim);
  
      const timeoutId = setTimeout(() => {
        Object.values(actions).forEach((action) => action.stop());
        actions.idle2.reset().play();
      }, timeAnim);
  
      return () => clearTimeout(timeoutId);
    } else {
      actions.idle2.reset().play();
    }
  }, [animation]);
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Mesh_0" geometry={nodes.Mesh_0.geometry} material={materials.Material_0} skeleton={nodes.Mesh_0.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(path)
